### PR TITLE
Change default charset from utf8 to utf8mb4

### PR DESCRIPTION
**Pull request by ryantang333**

### CODE REVIEW

**Comment by bueltge** [comment]
Thanks a lot @ryantang333 
Have you used the master branch version for s/r test in your environment? Currently we have a lot of changes in this branch, especially in the search&replace of serialized data and it would be fine, if you can help us to test this. Is an important change for more security. All other tools and plugins in this context have the same source base with the same security problem.

**Comment by ryantang333** [comment]
@bueltge I actually did try using the master branch (I saw that you added csv support!) however it didn't work and I didn't really look into it. For the time being I'm actively using 3.1.2. However, I am in need of that csv support for multiple search and replace in one go, so I may continue to look at the master branch.

**Comment by bueltge** [comment]
The csv importer is not the important topic, more special for different users. The search/replace from data in serialized form is the important think, that we changed and that should also work, like data in post meta.

**Comment by ryantang333** [comment]
The standard search and replace is not working currently.

On a search and replace specifically targeting serialized data on a dry
run, this is what happens:
[image: Inline image 1]

On a search and replace specifically targeting serialized data with an
output sql file, the result file shows no replacements made.

On a normal search and replace with either dry run or output sql file the
following error is returned: Catchable fatal error: Object of class
__PHP_Incomplete_Class could not be converted to string in
/Users/ryantang/Web/nim-web-cms/src/plugins/search-and-replace-master/inc/Database/Replace.php
on
line 355

On a csv search and replace (both dry and sql) targeting only serialized
data, nothing is being replaced.

On a csv search and replace on fields with both serialized and non
serialized, dry runs give the same Catchable fatal error as above for
line *354,
*and sql runs don't show the typical "x lines changed" message but have a
sql file that has all unserialized fields properly replaced, but no change
to serialized data.

I'm on the master branch, latest commit.

**Comment by ryantang333** [comment]
I've realized that a majority of my issues are because my PHP version is
set to 5.5.3, and therefore calls to unserialize return with
__PHP_Incomplete_Class errors instead of false.

**Comment by bueltge** [comment]
Thanks for the hint to the error. Can you switch to 5.6? Can you also add the image above, then is current missing.

**Comment by ryantang333** [comment]
I just tested on 5.6.22 and 7.1.11 but I still get the same error with
__PHP_Incomplete_Object. However, when I change line 312 on
inc/Database/Replace.php to pass false as a second parameter in the
unserialize call, I get no error. According to
http://php.net/manual/en/function.unserialize.php for the *options *param:

Either an array <http://php.net/manual/en/language.types.array.php> of
class names which should be accepted, FALSE to accept no classes, or TRUE to
accept all classes. If this option is defined and unserialize()encounters
an object of a class that isn't to be accepted, then the object will be
instantiated as __PHP_Incomplete_Class instead. Omitting this option is the
same as defining it as TRUE: PHP will attempt to instantiate objects of any
class.

After this, unserialized fields get properly replaced. For serialized
fields, the '|' character is being added. The CSV export also does not
replace anything.

Ryan

**Pull request merged**
