### PR TITLE
master

### PR DESCRIPTION
**Pull request by widoz**
Fix: undefined function `___` use `esc_html_e` instead

### CODE REVIEW

**Comment by bueltge** [comment]
As alternate, much solid is `wp_kses`. See also my cheat sheet https://gist.github.com/bueltge/49c652187ef10a448bfb

**Comment by widoz** [comment]
I realized that in some circunstances extracting the html from the string may put the meaning of the text outside of the context and that should mean using an extra call to `esc_html_x`. 

So I think `wp_kses` will be much better than escaping. Yay! Thanks for the advice.

In case can I'm free to change those string that include the escape to using wp_kses?

**Comment by bueltge** [comment]
Feel free to create a better source. But advice, important is a solid search replace release and after this release we should change source topics. Currently is it important to release the security issue and open bugs. Thx!

**Comment by widoz** [comment]
Of course. Thanks

**Comment by bueltge** [comment]
Thank you!

**Pull request merged**
