### PR TITLE
phpcs

### PR DESCRIPTION
**Pull request by widoz**

### CODE REVIEW

**Comment by widoz** [comment]
One doubt about the `testVersion` value. 

We should keep 7.0 or stay within the 5.6 that is actually the minimum version required for the plugin according with PHPCompatibility?

**Comment by widoz** [comment]
It say 

```
PHP Fatal error:  Uncaught PHP_CodeSniffer_Exception: Referenced sniff "WordPress.NamingConventions.ValidHookName" does not exist in /home/travis/build/inpsyde/search-and-replace/vendor/squizlabs/php_codesniffer/CodeSniffer.php:1167

Stack trace:

#0 /home/travis/build/inpsyde/search-and-replace/vendor/squizlabs/php_codesniffer/CodeSniffer.php(780): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), '/home/travis/bu...', 0)

#1 /home/travis/build/inpsyde/search-and-replace/vendor/squizlabs/php_codesniffer/CodeSniffer.php(578): PHP_CodeSniffer->processRuleset('/home/travis/bu...')

#2 /home/travis/build/inpsyde/search-and-replace/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(956): PHP_CodeSniffer->initStandard(Array, Array, Array)

#3 /home/travis/build/inpsyde/search-and-replace/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(113): PHP_CodeSniffer_CLI->process()

#4 /home/travis/build/inpsyde/search-and-replace/vendor/squizlabs/php_codesniffer/scripts/phpcs(25): PHP_CodeSniffer_CLI->runphpcs()

#5 {main}

  in /home/travis/build/inpsyde/search-and-replace/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 1167
```

but "WordPress.NamingConventions.ValidHookName" exists and it's a valid rule.

**Comment by bueltge** [comment]
I would personally switc hto php7, but currently is it not an good idea, so that we support 5.6. Thx!

I have the same error on the phpcs ruleset since my last php update on the local machine to php 7.1*  :(

**Comment by bueltge** [comment]
Here, my error with the phpcs.ruleset.xml 
`ERROR: Referenced sniff "WordPress.NamingConventions.ValidHookName" does not exist` also in all other development projects. phpcs works without `--standard` parameter, but not with a parameter. :(

**Comment by widoz** [comment]
Uhm, I took the rules from https://github.com/inpsyde/php-coding-standards but no errors on my phpstorm installation nor running `phpcs`. 

For errors I mean, fatal error executing the command, I get correctly the errors from standards check.

I've installed globally `wpcs` and the `PHP_CodeSniffer` that include psr*, Squizz etc...

Here my standards list:

`The installed coding standards are PEAR, Zend, PSR2, MySource, Squiz, PSR1, WordPress-VIP, WordPress, WordPress-Extra, WordPress-Docs, WordPress-Core, wppsr and PHPCompatibility`

wppsr is a custom one for my projects. 

Btw, may be the issue came from the version used for `"wp-coding-standards/wpcs"` within the project, that actually download the `0.6.0` the latest is `0.14.0`.

Infact if you have a look at https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases the `WordPress.NamingConventions.ValidHookName` sniffer (if I understand correctly) is introduced in `0.10.0`.

Changelog say:

```
WordPress.NamingConventions.ValidHookName sniff to the WordPress-Core ruleset to flag filter and action hooks which don't comply with the guideline of lowercase letters and underscores. For maintaining backward-compatibility of hook names an additionalWordDelimiters property can be added via a custom ruleset.
```

**Comment by bueltge** [comment]
I think I have an other problem. Also the switch to `"wp-coding-standards/wpcs": "^0.13.1",` is not helpful. Composer is globally active on my client.

**Comment by widoz** [comment]
What `phpcs -i` show you? 

For the version of `wpcs` should solve the issue with travis.

**Comment by widoz** [comment]
Hi, I got this new one issue after clone the repository, not quite sure what the problem here.

```
PHP Code Sniffer
					phpcs: Can not correctly run the tool with parameters:
					/private/var/folders/5c/9wx2h9r56xb1nknw1wc2tqgr0000gn/T/phpcs_temp.tmp/inpsyde-search-replace.php
					--standard=/Users/guido/Me/Development/inpsyde/search-and-replace/phpcs.ruleset.xml
					--encoding=utf-8
					--report=xml
					Possible tool process hangup after 30 sec.
```

After

**Comment by widoz** [comment]
Uhm, seems a rethinking of dependencies is needed:

>  Problem 1
>
>    - phpunit/phpunit 6.3.1 requires php ^7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
>
>    - phpunit/phpunit 6.3.0 requires php ^7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
>
>    - Installation request for phpunit/phpunit 6.3.* -> satisfiable by phpunit/phpunit[6.3.0, 6.3.1].

and this happened in my installation too

``` 
The command "composer install --no-progress --prefer-source" failed and exited with 2 during .
```

That I resolved by recreate the autoload. 

Ps. It's really necessary to push the vendor autoloader?

**Comment by widoz** [comment]
I created a new issue where we can continue the discussing of phpunit version https://github.com/inpsyde/search-and-replace/issues/109

**Comment by bueltge** [comment]
I have also this errors, I will try your helpful comments.

**Pull request merged**
